# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'')),
                ('userDescription', models.CharField(max_length=140, null=True)),
                ('pubDate', models.DateTimeField(null=True, verbose_name='pubDate')),
            ],
        ),
        migrations.CreateModel(
            name='augmentedImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageStyles.Image')),
                ('options', models.CharField(max_length=200)),
            ],
            bases=('imageStyles.image',),
        ),
        migrations.CreateModel(
            name='originalImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageStyles.Image')),
            ],
            bases=('imageStyles.image',),
        ),
        migrations.AddField(
            model_name='augmentedimage',
            name='originalImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageStyles.originalImage'),
        ),
    ]
