# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='augmentedImageOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='generatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('model_path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='generatingModelStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=140)),
                ('image', models.ImageField(upload_to=b'')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageStyles.generatingModel')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'')),
                ('userDescription', models.CharField(max_length=140, null=True)),
                ('pubDate', models.DateTimeField(null=True, verbose_name='pubDate')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='augmentedImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageStyles.Image')),
                ('thumbnail', models.ImageField(upload_to=b'')),
            ],
            bases=('imageStyles.image',),
        ),
        migrations.CreateModel(
            name='originalImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageStyles.Image')),
            ],
            bases=('imageStyles.image',),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='augmentedimageoptions',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageStyles.generatingModel'),
        ),
        migrations.AddField(
            model_name='augmentedimageoptions',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageStyles.generatingModelStyle'),
        ),
        migrations.AddField(
            model_name='augmentedimage',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageStyles.augmentedImageOptions'),
        ),
        migrations.AddField(
            model_name='augmentedimage',
            name='originalImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageStyles.originalImage'),
        ),
    ]
