# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageStyles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augmentedimage',
            name='originalImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageStyles.originalImage'),
        ),
    ]
